version: 2
models:
  - name: dim_listings_with_hosts
    columns:
    - name: listing_id
      description:  'test'
      tests:
      - unique
      - not_null
    - name: price    
      tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: number
        - dbt_expectations.expect_column_quantile_values_to_be_between:
            quantile: .99
            min_value: 50 # (Optional)
            max_value: 500 # (Optional)
        - dbt_expectations.expect_column_max_to_be_between:
            max_value: 5000
            config:
              severity: warn
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: src_listings #source('airbnb','listings')

  - name: dim_hosts_cleansed
    description: Cleansed table for hosts from airbnb data
    columns:
    - name: host_id
      description:  '{{ doc("dim_hosts_cleansed")}}'

  - name: dim_listings_cleansed
    description: Cleansed table which contains airbnb data
    columns:
    - name: listing_id
      description: Primary key for the listings
      tests:
        - unique
        - not_null
    - name: host_id
      description: Primary key for hosts
      tests:
      - not_null
      - relationships:
          to: ref('dim_hosts_cleansed')
          field: host_id
    - name: room_type
      description: Check the room typ by whatever
      tests:
        - accepted_values:
            values: ['Entire home/apt',
                    'Private room',
                      'Shared room',
                      'Hotel room']
    - name: minimum_nights
      description: '{{ doc("dim_listing_cleansed__minimum_nights")}}'
      tests:
        - positive_value
    - name: dim_hosts_cleansed
      columns:
        - name: host_id
          tests:
            - not_null
            - unique
        - name: host_name
          tests:
            - not_null
        - name: is_superhost
          tests:
            - accepted_values:
                values: ['t', 'f']



















