version: 2
models:
  - name: dim_hosts_cleansed
    description: Cleansed table for hosts from airbnb data
    columns:
    - name: host_id
      description:  '{{ doc("dim_hosts_cleansed")}}'
  - name: dim_listings_cleansed
    description: Cleansed table which contains airbnb data
    columns:
    - name: listing_id
      description: Primary key for the listings
      tests:
        - unique
        - not_null

    - name: host_id
      description: Primary key for hosts
      tests:
      - not_null
      - relationships:
          to: ref('dim_hosts_cleansed')
          field: host_id
    - name: room_type
      description: Check the room typ by whatever
      tests:
        - accepted_values:
            values: ['Entire home/apt',
                    'Private room',
                      'Shared room',
                      'Hotel room']
    - name: minimum_nights
      description: '{{ doc("dim_listing_cleansed__minimum_nights")}}'
      tests:
        - positive_value
    - name: dim_hosts_cleansed
      columns:
        - name: host_id
          tests:
            - not_null
            - unique
        - name: host_name
          tests:
            - not_null
        - name: is_superhost
          tests:
            - accepted_values:
                values: ['t', 'f']
    - name: dim_hosts_cleansed
      columns:
        - name: host_id
          tests:
            - not_null
            - unique
        - name: host_name
          tests:
            - not_null
        - name: is_superhost
          tests:
            - accepted_values:
                values: ['t', 'f']
    - name: dim_hosts_cleansed
      columns:
        - name: host_id
          tests:
            - not_null
            - unique
        - name: host_name
          tests:
            - not_null
        - name: is_superhost
          tests:
            - accepted_values:
                values: ['t', 'f']